language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.02 PINS="mirage-block-unix mirage-types"
  - OCAML_VERSION=4.03 PINS="mirage-block-unix mirage-types"
